sonar.projectKey=vox-frontend
sonar.projectName=vox — Frontend (React)
sonar.projectVersion=1.0
sonar.organization=vox-frontend


# Source & test directories
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.tsx,**/*.spec.tsx,**/*.test.ts,**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,build/**,coverage/**,**/*.d.ts,public/**

# Coverage report
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.tsx,**/*.spec.tsx,**/__mocks__/**

sonar.language=js
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true