sonar.projectName=vox
sonar.projectKey=ravinder77_vox
sonar.projectVersion=1.0
sonar.organization=ravinder77

sonar.sources=backend/src,frontend/src
sonar.tests=backend/tests,frontend/src
sonar.test.inclusions=backend/tests/**/*.ts,frontend/src/**/*.test.tsx,frontend/src/**/*.spec.tsx,frontend/src/**/*.test.ts,frontend/src/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.d.ts,frontend/public/**,frontend/src/test/**,frontend/src/hooks/**,frontend/src/main.tsx,frontend/src/types/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.coverage.exclusions=backend/tests/**,frontend/src/**/*.test.tsx,frontend/src/**/*.spec.tsx,frontend/src/**/*.test.ts,frontend/src/**/*.spec.ts,backend/src/server.ts,backend/src/realtime/socket.ts

sonar.language=js
sonar.sourceEncoding=UTF-8
