
replicaCount: 1
clusterName:

region: ap-south-1
vpcId:

serviceAccount:
  create: true
  name: aws-load-balancer-controller

controllerConfig:
  featureGates:
    ALBGatewayAPI: true
    NLBGatewayAPI: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

enableShield: false
enableWaf: false
enableWafv2: true
logLevel: info
