apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: voxchat-gateway-defaults
  namespace: voxchat
spec:
  defaultConfiguration:
    targetType: ip
    targetGroupAttributes:
      - key: deregistration_delay.timeout_seconds
        value: "60"
---
apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: voxchat-gateway-lb
  namespace: voxchat
spec:
  scheme: internet-facing
  ipAddressType: ipv4
  defaultTargetGroupConfiguration:
    name: voxchat-gateway-defaults
  tags:
    team: voxchat
    managed-by: gateway-api
  listenerConfigurations:
    - protocolPort: HTTPS:443
      sslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: voxchat-gateway
  namespace: voxchat
  annotations:
    external-dns.alpha.kubernetes.io/hostname: voxchat.in,api.voxchat.in
spec:
  gatewayClassName: voxchat-gateway-class
  infrastructure:
    parametersRef:
      group: gateway.k8s.aws
      kind: LoadBalancerConfiguration
      name: voxchat-gateway-lb
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same

    - name: https
      hostname: "*.voxchat.in"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
      allowedRoutes:
        namespaces:
          from: Same

    - name: https-root
      hostname: "voxchat.in"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
      allowedRoutes:
        namespaces:
          from: Same
