{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ required "gateway.name is required" .Values.gateway.name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{ include "gateway.labels" . | nindent 4 }}
  {{- if or .Values.gateway.externalDns.enabled .Values.gateway.annotations }}
  annotations:
    {{- if .Values.gateway.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "gateway.externalDnsHostnames" . | quote }}
    {{- end }}
    {{- with .Values.gateway.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  gatewayClassName: {{ required "gatewayClass.name is required" .Values.gatewayClass.name | quote }}
  {{- if .Values.loadBalancerConfiguration.enabled }}
  infrastructure:
    parametersRef:
      group: gateway.k8s.aws
      kind: LoadBalancerConfiguration
      name: {{ required "loadBalancerConfiguration.name is required" .Values.loadBalancerConfiguration.name | quote }}
  {{- end }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ required "gateway.listeners[].name is required" .name | quote }}
      {{- with .hostname }}
      hostname: {{ . | quote }}
      {{- end }}
      port: {{ required "gateway.listeners[].port is required" .port }}
      protocol: {{ required "gateway.listeners[].protocol is required" .protocol }}
      allowedRoutes:
        namespaces:
          {{- toYaml (default $.Values.gateway.allowedRouteNamespaces .allowedRouteNamespaces) | nindent 10 }}
    {{- end }}
{{- end }}
