{{- if .Values.gatewayClass.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ required "gatewayClass.name is required" .Values.gatewayClass.name | quote }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  controllerName: {{ required "gatewayClass.controllerName is required" .Values.gatewayClass.controllerName | quote }}
{{- end }}
