pipeline {
    agent any
    tools {
        nodejs "Node-24"
    }

    // Parameters
    parameters {
        choice(
            name: 'ENVIRONMENT',
            choices: ['dev', 'staging', 'prod'],
            description: 'Target enviroment for deployment'
        )
        booleanParam(
            name: 'SKIP_TESTS',
            defaultValue: false,
            description: 'skip tests (emergency use only)'
        )
    }
    // Environment
    environment {

        GIT_CREDS= credentials('git-credentials')

        REGISTRY = 'docker.io/ravinder50300'
        REGISTRY_CREDS= credentials('dockerhub-credentials')

        FRONTEND_IMAGE = ''
        BACKEND_IMAGE = ''
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        timestamps()
        ansiColor('xterm')
    }



    stages {
        stage('Checkout') {
            steps {
                script {
                    sh 'checkout scm'
                }
            }
        }


        stage('') {}


        stage('') {}


        stage('') {}


        stage('') {}


        stage('') {}


        stage('') {}
    }
}