{{- if .Values.targetGroupConfiguration.enabled -}}
apiVersion: gateway.k8s.aws/v1beta1
kind: TargetGroupConfiguration
metadata:
  name: {{ include "frontend.serviceName" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  targetReference:
    name: {{ include "frontend.serviceName" . }}
  defaultConfiguration:
    targetType: {{ .Values.targetGroupConfiguration.targetType | quote }}
    protocol: HTTP
    healthCheckConfig:
      healthCheckPath: {{ .Values.targetGroupConfiguration.healthCheck.path | quote }}
      healthCheckPort: {{ .Values.targetGroupConfiguration.healthCheck.port | quote }}
      healthCheckProtocol: http
      healthCheckInterval: {{ .Values.targetGroupConfiguration.healthCheck.interval }}
      healthCheckTimeout: {{ .Values.targetGroupConfiguration.healthCheck.timeout }}
      healthyThresholdCount: {{ .Values.targetGroupConfiguration.healthCheck.healthyThresholdCount }}
      unhealthyThresholdCount: {{ .Values.targetGroupConfiguration.healthCheck.unhealthyThresholdCount }}
      matcher:
        httpCode: {{ .Values.targetGroupConfiguration.healthCheck.successCodes | quote }}
{{- end }}
